parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true
    bind:
      $resultDir: '%kernel.project_dir%/public/data/result'
      $sourceDir: '%kernel.project_dir%/public/data/source'
      $resultFile: '%kernel.project_dir%/public/data/result/result.csv'
      $logFile: '%kernel.project_dir%/public/data/result/log.txt'

  App\:
    resource: '../src/'
